import { chromium } from "playwright-core";
const OUT = process.argv[2];
const home = process.env.USERPROFILE || process.env.HOME;
const exe = `${home}\\AppData\\Local\\ms-playwright\\chromium-1228\\chrome-win64\\chrome.exe`;
const b = await chromium.launch({ executablePath: exe });
const ctx = await b.newContext({ viewport: { width: 1280, height: 820 }, reducedMotion: "reduce", deviceScaleFactor: 1.5 });
const p = await ctx.newPage();
await p.goto("http://localhost:3126/", { waitUntil: "load" });
await p.waitForTimeout(700);
await p.locator("main section").nth(3).scrollIntoViewIfNeeded();
await p.waitForTimeout(700);
await p.locator("main section").nth(3).screenshot({ path: `${OUT}/blue-saude.png` });
await p.locator("main section").nth(6).scrollIntoViewIfNeeded();
await p.waitForTimeout(500);
await p.locator("main section").nth(6).screenshot({ path: `${OUT}/blue-assoc.png` });
await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await p.waitForTimeout(700);
await p.locator("footer").screenshot({ path: `${OUT}/blue-footer.png` });
await b.close();
console.log("done");
